### ISSUE TITLE
Invalid history size

### ISSUE THREAD

**Issue by ranebrown** [riscy/command_line_lint#3]
I wanted to give your script a try but I am getting the following error.

```
HISTSIZE            => ""
Traceback (most recent call last):
  File "command_line_lint.py", line 481, in <module>
    main()
  File "command_line_lint.py", line 473, in main
    report_overview()
  File "command_line_lint.py", line 65, in report_overview
    _print_environment_variable('HISTSIZE')
  File "command_line_lint.py", line 374, in _print_environment_variable
    lint()
  File "command_line_lint.py", line 290, in increase_histsize
    histsize_val = int(os.environ.get('HISTSIZE', '0'))
ValueError: invalid literal for int() with base 10: ''
```

I believe this is occurring because I have HISTFILESIZE and HISTSIZE set to empty strings to have unlimited history size. `HISTFILESIZE=` and `HISTSIZE=`

Also curious if using this time format will cause other issues? `HISTTIMEFORMAT="[%a %h %d – %r] "`

Thanks!

**Comment by thezeroalpha** [comment]
Opened #4 to deal with `HISTSIZE` and `HISTFILESIZE` being blank/invalid. For now it uses -1 to signify unlimited size, but if you think a different value is better, I can change it.

**Edit:** `HISTTIMEFORMAT` does not seem to add anything to the actual history file, which is what's being read in the script. If I query `history`, I get results with the timestamp in the respective format, but the history file still only contains the executed commands. Therefore, I don't think having `HISTTIMEFORMAT` set would cause any issues (but please do correct me if I'm wrong). Also, I tested it on bash and zsh, but it might not be the case for all shells. It does not seem to impact zsh at all.

**Comment by riscy** [comment]
Thanks very much @thezeroalpha for the improvements in #4.  About to hit merge.

I think, in bash, setting `HISTTIMEFORMAT` will add lines along the lines of `# <unix_epoch_time>` to the history file, but any such lines are ignored in this script.  It looks like the `history` command will use `HISTTIMEFORMAT` in its output to generate lines that look like this:
```bash
  ...
  501  2019-01-14 18:34:44 pwd
  ...
```

zsh's timestamps, on the other hand, look like they're inlined into the `.history` file, which @thezeroalpha has already fixed. :)

**Comment by riscy** [comment]
@ranebrown Hopefully the latest master works for you now.  Sorry about that. :)

**Comment by ranebrown** [comment]
No worries! Thanks for the quick responses, seems to be working now.
